using FxEvents.Shared.Attributes;
using System.IO;

namespace FxEvents.Shared.Payload
{
    public class EventParameter
    {
        public byte[] Data { get; set; }

        public EventParameter(byte[] data)
        {
            Data = data;
        }
        public EventParameter(BinaryReader reader)
        {
            UnpackSerializedBytes(reader);
        }
        public void PackSerializedBytes(BinaryWriter writer)
        {
            // Auto-generated by the Serialization Generator. Created by Lucas mantained by Manups4e.
            writer.Write(Data is not null);
            if (Data is not null)
            {
                writer.Write(Data.Length);
                writer.Write(Data);
            }
        }
        public void UnpackSerializedBytes(BinaryReader reader)
        {
            // Auto-generated by the Serialization Generator. Created by Lucas mantained by Manups4e.
            if (reader.ReadBoolean())
            {
                var dataLength = reader.ReadInt32();
                Data = reader.ReadBytes(dataLength);
            }
        }
    }
}